version: '3.4'

services:
  authservice:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 4000:4000
    volumes:
      - /app/node_modules
      - .:/app
  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
