version: 2.1

obs:
  node: circleci/node@5.0.2

jobs:
  build_and_test:
    steps:
      - checkout
      - run:
          command: npm install
          name: Install packages
      - run:
          command: npm run test
          name: Run tests
      - run:
          command: npm run build
          name: Run build
      - persist_to_workspace:
          root: ~/project
          path:
            - .

workflows:
  build_and_test:
    jobs:
      - build_and_test