version: 2.1

obs:
  node: circleci/node@5.0.2

jobs:
  build-and-test:
    executor: node/default

    steps:
      - checkout
      - node/install-packages:
        pkg-manager: npm
      - run:
        command: npm run test
        name: Run tests
      - run:
        command: npm run build
        name: Run build
      - persist_to_workspace:
        root: ~/project
        path:
          - .

workflow:
  build-and-test:
    jobs:
      - build-and-test